### ISSUE TITLE
Implement Scenario Comparison Results

### ISSUE THREAD

**Issue by ansoncfit** [mitTransportAnalyst/CoAXs#10]
Return comparison vector and tile isochrones.  
Show both histogram lines.

**Comment by kuanb** [comment]
The two geojsons are on top of each other but different colors... this is how it is done in trans analyst right now

**Comment by ansoncfit** [comment]
![Uploading 2015-07-09 17.58.42.jpg…]()
![2015-07-09 17 58 49](https://cloud.githubusercontent.com/assets/2173529/8620064/13ec6c5e-26eb-11e5-9ec5-f21b2dccddc3.jpg)

**Comment by ansoncfit** [comment]
![2015-07-09 17 58 42](https://cloud.githubusercontent.com/assets/2173529/8620104/51cb7cd6-26eb-11e5-81e6-440475c5fc35.jpg)
![2015-07-09 17 58 49](https://cloud.githubusercontent.com/assets/2173529/8620103/51c9731e-26eb-11e5-90b4-160ca3e3feaf.jpg)

**Comment by ansoncfit** [comment]
How much additional work would it be to both cumulative opportunity plots to show?  Or to make the plot show the difference between the two scenarios in a comparison mode?

**Comment by ansoncfit** [comment]
Follow up on scenario comparisons:
The issue of vector isochrones from different origin locations appearing has resurfaced:
![capture](https://cloud.githubusercontent.com/assets/2173529/9039551/3edb6306-39ca-11e5-8f79-065c4dda121b.JPG) (initially waited for dropped pin to load at Alewife, then moved it to Blue Hill Ave., waited for loading bar to finish, then displayed vector isos again).

**Comment by kuanb** [comment]
Thanks will review next, after 29

**Comment by kuanb** [comment]
Also let's break this into 2, the ask for vector iso issue and the dual plot as a new issue.

**Comment by kuanb** [comment]
~1 hour

**Comment by kuanb** [comment]
https://github.com/mitTransportAnalyst/CoAXs/commit/a346eb6c5b53e76bb6d655e497a19e9bc11bf2de resolves
