### ISSUE TITLE
Put more workers on backend

### ISSUE THREAD

**Issue by Xin-Zheng** [mitTransportAnalyst/CoAXs#107]
Peter said if the AWS price is not so expensive, we could put more worker on the backend to speed up the calculation

**Comment by ansoncfit** [comment]
Our current workshops won't have more than four simultaneous requests (e.g. comparisons of two scenarios being submitted by the two screens at the same time), so I don't think there's any advantage to adding more than our current four cores.

**Comment by Xin-Zheng** [comment]
Got it~
