### ISSUE TITLE
Fix wait times not set on load (Phil's UI)

### ISSUE THREAD

**Issue by ansoncfit** [mitTransportAnalyst/CoAXs#11]
![pasted image at 2015_07_01 06_12 pm](https://cloud.githubusercontent.com/assets/2173529/8492197/5e07b622-2114-11e5-8fef-0cbf923120c3.png)

**Comment by mgpopinjay** [comment]
I can take a look at this NaN default display first.

**Comment by mgpopinjay** [comment]
Default "Avg Wait Time" now set as 00:00 

![screenshot](https://cloud.githubusercontent.com/assets/7353899/8640502/2a458582-28c9-11e5-84bf-6dabaee184c0.png)

**Comment by ansoncfit** [comment]
Can it be set to 2:30 for peak and 5:00 for off-peak?

Anson Stewart
