### ISSUE TITLE
Add Legend

### ISSUE THREAD

**Issue by ansoncfit** [mitTransportAnalyst/CoAXs#12]
For isochrone colors

**Comment by mgpopinjay** [comment]
I can do something like a floating legend.  Will take up to a day (a few minutes for Kuan).

**Comment by ansoncfit** [comment]
I was initially thinking we would need to use this: https://github.com/conveyal/analyst-server/blob/master/docs/api.md#legends.  But that won't be necessary until we implement the ability to display multi-point requests.

So for now, I think we just need two legends:
- For Vector Isos
  - [yellow box] Time Boundary (Selected Scenario) 
  - (if in comparison mode) [blue box] Time Boundary (Comparison Scenario) 
- For Raster Tile Isos
  - [Yellow to white gradient; grey] underlying "Faster" "Slower" "Unreachable"
  - (if in comparison mode) [purple to white gradient] underlying "Faster in Selected Scenario"

The rest of the icons (T stations, POIs) will be self-explanatory and emphasized in other parts of the workshop.

**Comment by kuanb** [comment]
![image](https://cloud.githubusercontent.com/assets/6053396/8964312/ea5422f8-35f2-11e5-8f2a-22c05184155a.png)

Trying to think of where to stick this. For the time being point of least resistance I think would be bottom left, to the left of the user IDs and above Travel Time

**Comment by ansoncfit** [comment]
Or upper right?  It would be fine if the Manager Controls and scorecard blocked the legend.

**Comment by kuanb** [comment]
ok

**Comment by kuanb** [comment]
looking something like this...
![image](https://cloud.githubusercontent.com/assets/6053396/8965456/afe84b74-35f9-11e5-9dbc-2c9ccfa9f863.png)

**Comment by kuanb** [comment]
https://github.com/mitTransportAnalyst/CoAXs/commit/d7b495712c4788b6a83826194dd0d600afd5b577 resolves
