### ISSUE TITLE
Allow mode selection

### ISSUE THREAD

**Issue by ansoncfit** [mitTransportAnalyst/CoAXs#14]
Transit vs. walking.  Appears that bike access to transit is not yet supported by Analyst Server.

**Comment by kuanb** [comment]
This is applied to the left side, right? We don't hard set that into a submitted scenario from the right map, I would imagine.

**Comment by ansoncfit** [comment]
Yes, this applies to the left side.  Part of the API request, but not affected by anything related to a given scenario.

**Comment by kuanb** [comment]
Kuan: Spend 5 minutes and see if this is easy / possible with current API.

**Comment by ansoncfit** [comment]
Expecting API endpoints in place next week.  For reference, 
- all MBTA (no routeTypes removed)
- local transit (commuter rail [gtfs route_type = 2] and ferry [gtfs route_type = 4] removed)
- bus (commuter rail, ferry, subway [gtfs route_type = 1], and light rail [gtfs route_type = 0] removed)
- walking (all routeTypes removed)

**Comment by ansoncfit** [comment]
And similar to #13 , this should be a one-off request.

All of the options in the Travel Time control panel section are one-off (i.e. not cached).  The cached results for the scenarios assume no removed routeTypes and peak service.

**Comment by kuanb** [comment]
All MBTA: 0, 1, 2, 3, 4, 5, 6, 7

Local Tranist: 0, 1, 3, 5, 6, 7

Bus: 3, 5, 6, 7

Walking: ~none~

**Comment by kuanb** [comment]
https://github.com/mitTransportAnalyst/CoAXs/commit/7710f64e236001dbc1b320220d963e726ed4ee0c resolves

**Comment by kuanb** [comment]
error on routeType alter and control against point snap logic

![image](https://cloud.githubusercontent.com/assets/6053396/9066906/361acb74-3aa8-11e5-9bf1-9eff49438625.png)

**Comment by kuanb** [comment]
fixed w: https://github.com/mitTransportAnalyst/CoAXs/commit/f34ba968b15dae33288ff2fdba698bc410f9a398
