### ISSUE TITLE
Make control panel destination icons change accessibility histogram

### ISSUE THREAD

**Issue by ansoncfit** [mitTransportAnalyst/CoAXs#15]

**Comment by kuanb** [comment]
What are the destination icons? Is this the 5 icons in the early mock up? Clicking them will then change the jobs histogram that is presently in the app?

**Comment by ansoncfit** [comment]
Yes, though the icons in the mock-up don't correspond exactly to what we'll want.  See:
![destinationtypes](https://cloud.githubusercontent.com/assets/2173529/8581050/34b37532-258c-11e5-8a7d-4f27a5df709f.png)

**Comment by kuanb** [comment]
Do we want ALL the ones available in the list? I presently support 

`var subjects = {
        workers_low  : 'smart_location_database.e_lowwagew',
        workers_med  : 'smart_location_database.e_medwagew',
        workers_high : 'smart_location_database.e_hiwagewk',
        jobs_tot     : 'smart_location_database.emptot',
        hh_zerocar   : 'smart_location_database.autoown0',
        totpop       : 'smart_location_database.totpop10',
      };`

Could I get a csv or other list of the all unique id's that are to be received in the format of the above? That is, just add or remove keys and their assoc. values for dict `subjects`.

**Comment by kuanb** [comment]
From anson: 

Also,
e8_ret10
e8_hlth10
e8_ed10

**Comment by kuanb** [comment]
85% completion of goal achieved via https://github.com/mitTransportAnalyst/CoAXs/commit/15c33681a4d88483de95147ad446600eda913982

Being pushed to staging server as well. Will complete tomorrow AM

**Comment by kuanb** [comment]
Unanswered ques still on Conveyal Slack...:

I had a question regarding the results data. On my responses, it’s appearing that `’smart_location_database.e_lowwagew’`, `’smart_location_database.e_medwagew’`, and  `‘smart_location_database.e_hiwagewk’` all are generating the same array values. Thoughts as to why this is happening perhaps?

Any ideas?

**Comment by kuanb** [comment]
Resolved - those 3 vals are not supported for the state of MA at this time... So I will remove them for now and add:
e8_ret10
e8_hlth10
e8_ed10

**Comment by kuanb** [comment]
from matt:
![image](https://cloud.githubusercontent.com/assets/6053396/8932973/6161c8f4-350e-11e5-9b1c-e0ff833ce6df.png)

**Comment by kuanb** [comment]
https://github.com/mitTransportAnalyst/CoAXs/commit/1e5ee75cbbfee6ee4f4de55b32e7c9eaceb3ca1a should have solved it. there is an edge case occuring where sometimes the drop down disappears when you move the marker a few times on the same scenario... i cant debug but will return to it later if it persists since im spending too long on it now

**Comment by kuanb** [comment]
this issue should have been resolved
