### ISSUE TITLE
Make checkbox next to route variant activate route

### ISSUE THREAD

**Issue by ansoncfit** [mitTransportAnalyst/CoAXs#17]
I think checking the checkbox should have the same effect as clicking as the variant name (i.e. activating the route path and stops)

**Comment by mgpopinjay** [comment]
I need to understand the controller logic of this part first.

**Comment by kuanb** [comment]
resolved https://github.com/mitTransportAnalyst/CoAXs/commit/200b61e11d516e39cab01009613adbca0eeac031
