### ISSUE TITLE
Send frequency modifications with Conveyal API request

### ISSUE THREAD

**Issue by ansoncfit** [mitTransportAnalyst/CoAXs#18]
When updating the frequency sliders, the routing request should include the modified frequency for the appropriate route.

**Comment by kuanb** [comment]
This ties in with issue 19 (https://github.com/mitTransportAnalyst/CoAXs/issues/19) I think. We want to incorporate the dwell times for each route on Conveyal API call.

**Comment by kuanb** [comment]
When we send in the modifications, do we want to submit the peak or off-peak times?

**Comment by ansoncfit** [comment]
Peak for now.  Ideally we should have a peak/off-peak toggle in the Travel Time menu.

**Comment by kuanb** [comment]
Cool let's make that a separate issue and Ill knock this one out for now with peak

**Comment by kuanb** [comment]
Resolved via https://github.com/mitTransportAnalyst/CoAXs/commit/b9b0a32958a3aeca9b9cc23445742328e1277497
