### ISSUE TITLE
Send dwell time modifications with Conveyal API request

### ISSUE THREAD

**Issue by ansoncfit** [mitTransportAnalyst/CoAXs#19]
When updating the station type, the routing request should include the modified dwell times for the appropriate route.

For now, let's use:
stopType = 0: dwellTime = 30
stopType = 1: dwellTime = 20
stopType = 2: dwellTime = 10

**Comment by kuanb** [comment]
This will involve a more complex route structure that includes associated data modifications for each stop. I will need to design this likely prior to implementation (applied to this and other components). Good to get the heads up about these components - discussion will help me sketch out what the data's architecture looks like.

**Comment by kuanb** [comment]
For reference: 
https://github.com/conveyal/analyst-server/blob/master/docs/api.md#adjusting-dwell-times
