### ISSUE TITLE
Allow stop (de)activation

### ISSUE THREAD

**Issue by ansoncfit** [mitTransportAnalyst/CoAXs#20]
Build toggle input into leaflet tooltip for BRT corridor stops, and send appropriate modification with routing request

**Comment by kuanb** [comment]
Can we confirm workflow: I click on a stop - I can then modify it's type. Making a modification updates that stop type and the corresponding icon that is shown.

**Comment by ansoncfit** [comment]
Or removes the stop entirely.

**Comment by ansoncfit** [comment]
More UI thinking needs to go into this.  Closing for now.
