### ISSUE TITLE
Implement tracking/logging library

### ISSUE THREAD

**Issue by ansoncfit** [mitTransportAnalyst/CoAXs#22]

**Comment by kuanb** [comment]
What sort of tracking would this be? Can this be expanded upon with a description?

**Comment by ansoncfit** [comment]
Ideally, we could log tap events and re-create a session.  Not sure if there's a web-based approach to this, or if a separate program running on the machine would be better.

**Comment by ansoncfit** [comment]
We'll have other ways of measuring user engagement.  Closing for now.
