### ISSUE TITLE
Save scenarios and their attributes

### ISSUE THREAD

**Issue by ansoncfit** [mitTransportAnalyst/CoAXs#25]
Associate each scenario with a session id.
Allow scenarios from a given session to be reloaded.

**Comment by kuanb** [comment]
A function that downloads a JSON describing every aspect and score of a all scenarios in a session.

**Comment by kuanb** [comment]
Examine a "quick and dirty solution" and get back on the time on that.

**Comment by kuanb** [comment]
~1-3 hrs

**Comment by kuanb** [comment]
Example of what it is looking like now: 
![image](https://cloud.githubusercontent.com/assets/6053396/9067709/2b9ed802-3aad-11e5-8f7a-184bc5069ae4.png)

Not super useful atm, but will aim to replace `"BH":"7561e208-9087-455d-bedb-2b3d53001c81",` each with something more useful

**Comment by kuanb** [comment]
I think this is a point of 'legibility' that is useful to you guys:

![image](https://cloud.githubusercontent.com/assets/6053396/9068509/ddf15f9e-3ab1-11e5-9c44-954dd586e216.png)

Please let me know if you want more detail...
https://github.com/mitTransportAnalyst/CoAXs/commit/034b4ec96cd933e387cd86690750d67852e314b1 resolves this issue up to this point
