### ISSUE TITLE
Save Variant button disappears when modifying Blue Hill 0 or Hyde Park 0 alternatives

### ISSUE THREAD

**Issue by ansoncfit** [mitTransportAnalyst/CoAXs#28]

**Comment by ansoncfit** [comment]
<img width="960" alt="c1" src="https://cloud.githubusercontent.com/assets/2173529/8607131/da8db29c-265e-11e5-86b4-f6f71aeb7d62.png">
<img width="960" alt="c2" src="https://cloud.githubusercontent.com/assets/2173529/8607134/dd70997a-265e-11e5-9838-467352854781.png">

**Comment by kuanb** [comment]
Commits

https://github.com/mitTransportAnalyst/CoAXs/commit/2eda18ef1cde14e6002b4f1631982b6621be2ddf 
&
https://github.com/mitTransportAnalyst/CoAXs/commit/13007b57619b365f7f556f90a16f342cea0ec001

resolves.
