### ISSUE TITLE
Move variant/scenario-saving input box from top to the bottom of the screen.

### ISSUE THREAD

**Issue by mgpopinjay** [mitTransportAnalyst/CoAXs#29]

**Comment by kuanb** [comment]
This is just the input box, we want in on the bottom half of the screen so people can click it.

**Comment by kuanb** [comment]
https://github.com/mitTransportAnalyst/CoAXs/commit/f3d2b32feb0e999fba59ea74ff4a732cac83d91f

https://github.com/mitTransportAnalyst/CoAXs/commit/96ecc701123900f38a69f15ce6532ad202233337

resolves
