### ISSUE TITLE
Cache/snap single point requests for/to "home" POIs

### ISSUE THREAD

**Issue by ansoncfit** [mitTransportAnalyst/CoAXs#35]
Pre-loaded points should have single-point requests made and stored.  Maybe an "admin" option to update these POIs (instead of on load) would avoid messiness?

**Comment by kuanb** [comment]
Please provide a list of these points. I will make up a list now of arbitrary points but if there is any meta data required on top, etc, then we should incorporate those. I'll mock up a base version here:

It will be a list of Objects, such that: `[Object, Object, Object, ...]`

Each obj will be = `{ loc: {lat: 23.23, lng: 13.45}, id: 'StringName' }`

**Comment by kuanb** [comment]
I'll add the 1st version to https://github.com/mitTransportAnalyst/altShapefiles and you can update there.

**Comment by ansoncfit** [comment]
Can you pull the home locations from Phil's Google Spreadsheet?

**Comment by ansoncfit** [comment]
Or get the lat/lon of the home-tagged leaflet markers?

**Comment by kuanb** [comment]
Do you want me to live pull them or just use the ones we are currently using from there?

**Comment by ansoncfit** [comment]
Ideally the former; but if that adds too much complexity, then the latter.

**Comment by kuanb** [comment]
OK I had to restructure the internal GeoJSON requesting system just now but I am going to see if this is effective in accomplishing that ask.

**Comment by kuanb** [comment]
This commit resolves the update and caching of geojsons: https://github.com/mitTransportAnalyst/CoAXs/commit/d77211bc3826916f645bd034f459208bffd8f3d4

Now there is a new issue that needs to be created, which is placing that information on the map. I'll tackle this next (either tonight or tomorrow).

**Comment by kuanb** [comment]
https://github.com/mitTransportAnalyst/CoAXs/commit/9487502920922aa5365625c68d40c1f8750373b8
https://github.com/mitTransportAnalyst/CoAXs/commit/40da1e62673ed232a581d2a62dc8ad191bea32df
https://github.com/mitTransportAnalyst/CoAXs/commit/526b6719407ba077ce49d1faa6847adf1df63b86

Above all added to prior complete this issue. Sensitivity is set to 0.5 miles. I could also add in a toggle that lets you adjust sensitivity if we want

**Comment by kuanb** [comment]
![image](https://cloud.githubusercontent.com/assets/6053396/8963277/4d8942dc-35ed-11e5-97d2-84aaa8cff647.png)

Added in the manager controls. So sensitivity is set at 0.5 miles but it can be adjusted each session.
