### ISSUE TITLE
Add space between left and right side?

### ISSUE THREAD

**Issue by ansoncfit** [mitTransportAnalyst/CoAXs#38]
A few pixels so the maps are separated?

**Comment by kuanb** [comment]
Do we want just like a line over them or an actual space.. Ill just mock up one and we can react to it

**Comment by ansoncfit** [comment]
Either.  Just so it's clear the two maps are separate at first glance.

**Comment by mgpopinjay** [comment]
Kuan if u need to preserve time this is something i can clean up over the next week or so.

**Comment by kuanb** [comment]
ok

**Comment by kuanb** [comment]
resolved 
![image](https://cloud.githubusercontent.com/assets/6053396/8963688/6a2be050-35ef-11e5-893a-7cfac38cc420.png)
