### ISSUE TITLE
Make identifiers clearer in ID column

### ISSUE THREAD

**Issue by ansoncfit** [mitTransportAnalyst/CoAXs#39]
![capture](https://cloud.githubusercontent.com/assets/2173529/8948920/a94b252c-357a-11e5-9542-46c50c8dd264.JPG)

Tooltip may not be as helpful for touch.  Add two-letter corridor identifiers to boxes?  They won't be too small on a large screen.

**Comment by mgpopinjay** [comment]
Two-letters identifier in the box is probably the way to go.

**Comment by kuanb** [comment]
![image](https://cloud.githubusercontent.com/assets/6053396/8964285/be989f68-35f2-11e5-81e6-f8fea92052b0.png)

done
