### ISSUE TITLE
Add numeric feedback display to Scale A travel time scale (Vector Isos)

### ISSUE THREAD

**Issue by mgpopinjay** [mitTransportAnalyst/CoAXs#4]

**Comment by kuanb** [comment]
I need more information if this is something that you guys would like me to comment on.

**Comment by mgpopinjay** [comment]
This one is already implemented :)

<img width="192" alt="screenshot" src="https://cloud.githubusercontent.com/assets/7353899/8605544/0719c1d0-2654-11e5-9d6f-2d118977056c.png">

**Comment by kuanb** [comment]
awesome nice work
