### ISSUE TITLE
Calculate summary index from cached responses for home POIs

### ISSUE THREAD

**Issue by ansoncfit** [mitTransportAnalyst/CoAXs#43]
Number of opportunities accessible within 60 minutes for the average home POI (i.e. sum of cumulative opportunities divided by number of home POIs).

**Comment by kuanb** [comment]
This would be for the currently selected scenario (of preloads, and as a comparison against new scenarios)...

**Comment by ansoncfit** [comment]
Relies on #45

**Comment by kuanb** [comment]
~1.5 hrs

**Comment by kuanb** [comment]
Extract the val for 60 minutes only...
