### ISSUE TITLE
D3 cumulative plot should have two lines when comparing

### ISSUE THREAD

**Issue by ansoncfit** [mitTransportAnalyst/CoAXs#44]

**Comment by kuanb** [comment]
~1 hr

**Comment by kuanb** [comment]
This is taking actually a bit longer. Has to do with way compared values are stored. Aiming to finish though this evening.

**Comment by kuanb** [comment]
![image](https://cloud.githubusercontent.com/assets/6053396/9050602/67b6c4fc-3a1d-11e5-9ef3-4a3e6104fdda.png)

working

**Comment by kuanb** [comment]
https://github.com/mitTransportAnalyst/CoAXs/commit/e9ff84b18209433089d8b947b8e0cb13f1c48825

and

https://github.com/mitTransportAnalyst/CoAXs/commit/27fc576076be76376f9347c49837fed358979a12

resolve... havent debugged yet so will want to do that before i say it is full resolved

**Comment by kuanb** [comment]
![image](https://cloud.githubusercontent.com/assets/6053396/9050818/7b1709e6-3a20-11e5-9b43-9fa4d1a028d0.png)
 strange results with data, should review in am

**Comment by kuanb** [comment]
resolved above issue... but actual results arent really all that perceptible and that's withthe lightest line weight...
