### ISSUE TITLE
Allow bulk request (for home POIs) for selected scenario

### ISSUE THREAD

**Issue by ansoncfit** [mitTransportAnalyst/CoAXs#45]
i.e. not just baseline scenario.

**Comment by kuanb** [comment]
![image](https://cloud.githubusercontent.com/assets/6053396/9073263/3a4d301c-3ace-11e5-8cd6-8e8383ff309a.png)

logic is built to handle loading in jsons, next will be to update/create

**Comment by kuanb** [comment]
heads up for the future, logic to load 'baseline.json' will be very simple:

`if (data.indexOf('baseline.json') > -1) {
        $scope.snapPoints.sel = 'baseline.json';
      }`

This means it's important that you name whatever file you want to be the baseline as `baseline.json`

**Comment by kuanb** [comment]
https://github.com/mitTransportAnalyst/CoAXs/commit/2b3ac3d8044d924c20c23e622f2249b4501db8b9 supports updating any cached poi set

**Comment by kuanb** [comment]
https://github.com/mitTransportAnalyst/CoAXs/commit/68a0d320c4224b8d0c8df81ef448cfba432b2e57 supports fix for preMarkerQuery bug

**Comment by kuanb** [comment]
![image](https://cloud.githubusercontent.com/assets/6053396/9104396/49d504f8-3bda-11e5-9375-35d64c8bbb89.png)

3 commits for today support saving of files

![image](https://cloud.githubusercontent.com/assets/6053396/9104405/5fc3682c-3bda-11e5-9036-65f98c23c75d.png)

as you can see from image i created and named a file foobar.json and it saved into my directory

Now I have enabled direct access to the files, but accessing them is a bit janky but I think sufficient for "manager" access...

You access the directory by going to:
`http://localhost:3000/public/routes/shapefiles/mapApp/cached/foobar.json`

Where `http://localhost:3000/` is whatever you are running locally or the herokuapp

You will need to know what you named it and then append `.json` to the end of that and there will be your updated url endpt

I can build in a download feature from the manager toolkit too if the above system is too convoluted; let me know
