### ISSUE TITLE
Cumulative plot does not update when changing opportunity type

### ISSUE THREAD

**Issue by ansoncfit** [mitTransportAnalyst/CoAXs#46]
Changing from Total Jobs to "show with..." other opportunities works in comparison mode, but not in single scenario mode.

![fullscreen capture 842015 113414](https://cloud.githubusercontent.com/assets/2173529/9064950/f787d254-3a9c-11e5-8634-28721ffa791a.jpg)
![fullscreen capture 842015 113420](https://cloud.githubusercontent.com/assets/2173529/9064951/f7886dfe-3a9c-11e5-84eb-3e307b83369a.jpg)

**Comment by kuanb** [comment]
whoops sorry about that - typo in code, fixed with last commit
