### ISSUE TITLE
Create new station markers for Scale B map that's consistent with station editor buttons and Scale D editor

### ISSUE THREAD

**Issue by mgpopinjay** [mitTransportAnalyst/CoAXs#5]

**Comment by kuanb** [comment]
I am assuming these station markers are those that were provided for the bus stops? If so we are using ones supplied in final week push, so swapping them out is as easy as swapping out the contents that are in that public folder within which they reside.

**Comment by mgpopinjay** [comment]
It looks like we are going to work out a simpler design with dots of 3 sizes to represent the the stations on the map.   The tiny details of the icon just don't show well at that 20px scale on the map.

**Comment by mgpopinjay** [comment]
Duplicate of another issue.
