### ISSUE TITLE
Update Isos button returns only baseline scenario (except in comparison mode)

### ISSUE THREAD

**Issue by ansoncfit** [mitTransportAnalyst/CoAXs#50]
More general issue than #49.

In single scenario mode, vector isos are the same for A and B, even after hitting update isos button:
![fullscreen capture 842015 130346](https://cloud.githubusercontent.com/assets/2173529/9067118/9ac79524-3aa9-11e5-8a1f-befa1aeef4a3.jpg)
![fullscreen capture 842015 130409](https://cloud.githubusercontent.com/assets/2173529/9067119/9aca7c08-3aa9-11e5-9740-74e3caf86308.jpg)

But there is a substantial difference between them, as shown in comparison view (note that boundary for B should extend across the Charles into Cambridge):
![fullscreen capture 842015 130727](https://cloud.githubusercontent.com/assets/2173529/9067150/cb9654ce-3aa9-11e5-9044-455652ac17b8.jpg)

I also confirmed this occurs whether or not the origin marker is at a cached POI.  

It also occurs even when "wiggling" the origin marker.

**Comment by kuanb** [comment]
I can't recreate this but you definitely did, correct, in the call we just did?

**Comment by kuanb** [comment]
One possibility is that the version you were working with was the version prior to the fix I deployed online ~1.5 hrs ago...?

**Comment by kuanb** [comment]
Here is with A:
![image](https://cloud.githubusercontent.com/assets/6053396/9070740/675f7f60-3abf-11e5-897b-6223050b66bc.png)

And now with B:
![image](https://cloud.githubusercontent.com/assets/6053396/9070773/8b139e14-3abf-11e5-833b-5fad20df630e.png)

**Comment by kuanb** [comment]
and the dif

![image](https://cloud.githubusercontent.com/assets/6053396/9070802/a7ea468c-3abf-11e5-834c-c26021771a16.png)

**Comment by ansoncfit** [comment]
I don't think I'd refreshed within the 90 min before our call.

Seems to work for me now.
