### ISSUE TITLE
Fixes for cumulative plot

### ISSUE THREAD

**Issue by ansoncfit** [mitTransportAnalyst/CoAXs#52]
A. Vertical scale cut off (see below).
B. In comparison mode, the following behavior would seem to indicate a bug:
1. Comparison for two scenarios shows a visible difference in total jobs.  This is expected.

![j1](https://cloud.githubusercontent.com/assets/2173529/9258931/373f58b4-41cc-11e5-9cbc-34e39b70a02d.JPG)
1. When switching to education jobs, there does not appear to be a difference.  This is very plausible.  
   ![j2](https://cloud.githubusercontent.com/assets/2173529/9258965/5be3c65a-41cc-11e5-8725-d0084680ef7b.JPG)
2. When switching back to total jobs, the difference seen in 1 above is gone.  This seems buggy.
   ![j3](https://cloud.githubusercontent.com/assets/2173529/9258980/6c5d6f22-41cc-11e5-9cee-67e37d00e549.JPG)

**Comment by mgpopinjay** [comment]
Anson - after selecting the category from the drop down, did you click on the bar displaying the category name?  On my side the graph updates once you click on the bar.

**Comment by ansoncfit** [comment]
Yep, I did.  I can still reproduce this issue.  I think the problem is not that the graph doesn't update, but it is that, in comparison mode, it seems to update to something unexpected/incorrect (i.e. the slight difference between the first and third screenshots above)

**Comment by ansoncfit** [comment]
@mgpopinjay will update scale to show thousands to address axis cutoff issue.
@kuanb were you able to reproduce the comparison mode bug?

**Comment by mgpopinjay** [comment]
Updated the scale with "k" and "M" assignments --> no more cutoff issue.
![screenshot](https://cloud.githubusercontent.com/assets/7353899/9650013/0fb621ba-51cb-11e5-9643-56289e0498e3.png)

**Comment by ansoncfit** [comment]
Bug pulled out as separate issue (#76).
