### ISSUE TITLE
Move POIs on top of Vector Isochrones (Phil's UI)

### ISSUE THREAD

**Issue by ansoncfit** [mitTransportAnalyst/CoAXs#7]
Layering needs to be done so on click tooltip works

**Comment by kuanb** [comment]
The solution may be to remove and redraw the stops on every adjustment of the GeoJSON.

**Comment by mgpopinjay** [comment]
Potential phase 2 feature.  For the workshop being able to isolate individual participants markers will be sufficient for them to tell a story.  Logging pain-points and showing them on tool-tips is an attractive idea but will have more value when this platform gets deployed to crowdsource improvement opportunities.

**Comment by ansoncfit** [comment]
Tooltips are less necessary given icons.  Closing.

**Comment by kuanb** [comment]
should we rm tooltips?

**Comment by ansoncfit** [comment]
I think they're still useful to have (if not too resource intensive).  Just wanted to say it's not worth spending time getting them to show up above isochrones.
