### ISSUE TITLE
Replace BRT stop icons with simpler ones

### ISSUE THREAD

**Issue by ansoncfit** [mitTransportAnalyst/CoAXs#8]
Use descriptive icons in menu (in place of "normal", "platform", "BRT"), and simpler icons in menu and on map.

**Comment by kuanb** [comment]
Once provided this is a pretty simple UX fix, though we will want to have a solidified final design prior to making these sorts of implementations.

**Comment by kuanb** [comment]
@mgpopinjay send them over as svg's and ill prepare the correct png resolutions
