### ISSUE TITLE
Map labels (e.g. street names) should be on top of isochrone layers

### ISSUE THREAD

**Issue by ansoncfit** [mitTransportAnalyst/CoAXs#83]
http://leafletjs.com/examples/map-panes.html

**Comment by ansoncfit** [comment]
Also, Peter requested street names on the corridor editing map.

**Comment by ansoncfit** [comment]
Also, we the new mapbox layer to include water (so that water is shown on top of the vector isochrones, excluding areas that are accessible only by aquatic transport)

**Comment by Xin-Zheng** [comment]
got it.
